queries = {"asin_category_query": '''CREATE TABLE ASIN_Category
          (name_cat_lvl1 varchar,
           name_cat_lvl2 varchar,
           name_cat_lvl3 varchar,
           name_cat_lvl4 varchar,
           name_cat_lvl5 varchar,
           asin varchar unique); ''',
     
    'master_keywords_market_query': '''CREATE TABLE Master_KeyWords_Market_Insights
          (asin varchar,
           Keyword varchar UNIQUE,
           market_lifetime INT,
           avg_sales_listed INT,
           orders_per_month INT,
           avg_sales_per_month INT,
           active_competing_products INT,
           avg_price NUMERIC(5,2),
           estimated_profit_margin varchar,
           estimated_cogs varchar,
           market_maturity varchar,
           market_capacity varchar,
           market_competition varchar,
           market_fund varchar,
           market_concentration NUMERIC(5,2),
           market_activeness INT,
           sales_attribution_reviews INT,
           sales_attribution_price NUMERIC(5,2),
           sales_attribution_product_video NUMERIC(5,2),
           sales_attribution_Aplustcontent NUMERIC(5,2),
           sales_attribution_coupon NUMERIC(5,2),
           sales_attribution_time_listed NUMERIC(5,2),
           sales_attribution_customer_rating NUMERIC(5,2),
           sales_attribution_variation NUMERIC(5,2),
           sales_attribution_seller_type NUMERIC(5,2),
           sales_attribution_others NUMERIC(5,2),
           top10_order_per_day INT,
           top20_order_per_day INT,
           top50_order_per_day INT,
           top100_order_per_day INT,
           top10_min_reviews INT,
           top20_min_reviews INT,
           top50_min_reviews INT,
           top100_min_reviews INT); ''',
          
          
          'master_keywords_query_search_info': '''CREATE TABLE master_query_searchinfo
          (asin varchar,
           date varchar,
           Keyword varchar,
           MonthlyClick INT,
           MonthlyClickPct NUMERIC(5,2),
           MonthlySearch INT,
           MonthlySearchPct NUMERIC(5,2),
           SponsoredRank varchar,
           OrganicRank varchar); '''}

data = {
    "host"      : "test-wrapfy-1.c9dyjmixlq3h.us-east-2.rds.amazonaws.com",
    "database"  : "wrapfy_test",
    "user"      : "test_postgre_1",
    "password"  : "wrapfytesting",
    "port"      : "5432"
}
